### PR TITLE
Please review carefully as these changes impact the idea of the MVP

### LINKED ISSUE #21: Simplify the product idea which is far too complex and bizarre
thought again about what such a simple wrking exercise could be and mapping letters one on one is much better to 

1. translate into other languages 
2. actually use it for something
3. have more fun across the team

I will provide a pull request to change this for the better 😸

### PR DESCRIPTION
**Pull request by sthagen**
This PR closes issue #21

* Minimalized the MVP and now translate letters only to single letters, 
* added rot13 and random mapping, 
* added infrastructure for make and test

You can run make init (but should do that in a virtual env :-)

If you have pytest installed, you can now enter the python folder and execute the tests via

```bash
make test
```

Cf. the tests/test_cli.py for use cases ...

Some simple calls from within the python folder would be:

```bash
$ python -m letters_from_letters A B Z
('B', 'C', '?')

$ python -m letters_from_letters rot13 A B Z
('N', 'O', 'M')

$ python -m letters_from_letters random 42 A B Z
('J', 'W', 'O')

$ python -m letters_from_letters random A B Z
('u', 'x', 'r')

$ python -m letters_from_letters random A B Z
('q', 'y', 'j')

```

### CODE REVIEW

**Comment by WayneNani** [comment]
That changes a lot indeed.
I really appreciate the infrastructure updates.
Though, @AntonDrees put a lot of effort into expanding the previous letter_map.json, so I think we should await his review ;)

**Comment by sthagen** [comment]
We can try to have both, right? I can amend my commit accordingly. But, I will wait (I did not see the change in his fork, yet). @WayneNani Thank you for taking the time to review.

**Comment by sthagen** [comment]
I made some local changes including a json file with mappings of a single character/letter to an array of spaces and letters as before and it works. The tuple output I use temporarily to bootstrap testability makes such multi character/line output look ugly, but there is no reason why one should not map single letters to asciinator like letter displays 😉 

So, if there is a different json we can simply merge both change sets together (I accept pull requests also on my fork 🤕 🍴 ...)

Further, I will provide an additional change soon that prints the mappings out in a hopefully meaningful manner. Maybe probe the mapping when choosing the json as "tool" print vertically (to ease the start) and else horizontally.

Thinking even further we might also map all other "modes" more meaningfully as a 1 to 1 filter like so:

```
$ python -m letters_from_letters rot13 a bee
n orr
```
(if I got the rot13 correct in my head ...) - good idea?

**Review by AntonDrees — APPROVED** [review]
Looks fine to me.

**Pull request merged**
